'use strict';
const photoState={photos:[],editing:null,file:null,preview:null,retry:null,filterArticle:''};
const zoneNames={rayon:'Rayon',tg:'Tête de gondole',ilot:'Îlot central',produit:'Produit en situation',reserve:'Réserve'};
function photoTime(value){return value?new Date(value).toLocaleString('fr-FR',{day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Date non renseignée';}
function photoArticleOptions(selected='',all=false){return `<option value="">${all?'Tous les articles':'Vue générale · aucun article'}</option>`+(state.data?.articles||[]).map(a=>`<option value="${esc(a.itm8)}" ${a.itm8===selected?'selected':''}>${esc(a.libelle)} · ${esc(a.itm8)}</option>`).join('');}
async function loadPhotos(){
  try{const data=await api('/api/photos-contexte');photoState.photos=data.photos||[];$('photo-article-filter').innerHTML=photoArticleOptions(photoState.filterArticle,true);renderGallery();renderPhotoEditor();}
  catch(error){$('photo-gallery').innerHTML=`<div class="empty card">${esc(error.message)}</div>`;renderPhotoEditor();notice(error.message,'error');}
}
function renderGallery(){
  const zone=$('photo-zone-filter').value,article=$('photo-article-filter').value,from=$('photo-date-filter').value;photoState.filterArticle=article;
  const photos=photoState.photos.filter(p=>(!zone||p.zone===zone)&&(!article||p.itm8===article)&&(!from||p.date_photo>=from));
  $('photo-count').textContent=`${photos.length} photo${photos.length>1?'s':''} · triées par date de prise de vue · conservées sur ce PC`;
  $('photo-gallery').innerHTML=photos.length?photos.map(p=>`<article class="photo-card"><button class="photo-image" data-photo-open="${esc(p.id)}" aria-label="Agrandir ${esc(p.titre||'la photo')}"><img loading="lazy" src="${esc(p.thumbnail_url)}" alt="${esc(p.titre||zoneNames[p.zone]||'Photo du rayon')}"></button><div class="photo-card-body"><span class="eyebrow">${esc(zoneNames[p.zone])} · ${dateLabel(p.date_photo)}</span><h3>${esc(p.titre||p.libelle||'Vue du rayon')}</h3><p>${esc(p.commentaire||p.commentaire_auto)}</p>${p.changement?`<div class="photo-change">Changement : ${esc(p.changement)}</div>`:''}<div class="photo-card-footer"><small>${esc(p.libelle||'Vue générale')}</small><button class="text-button" data-photo-edit="${esc(p.id)}">Compléter →</button></div></div></article>`).join(''):'<div class="empty card photo-empty"><span aria-hidden="true">▧</span><h2>Le contexte commence ici.</h2><p>Photographiez une TG, une nouvelle implantation ou un produit dans son rayon. Ajoutez la date et ce que vous avez changé.</p></div>';
}
function renderPhotoEditor(){
  const p=photoState.editing||{};
  if(photoState.preview){URL.revokeObjectURL(photoState.preview);photoState.preview=null;}photoState.file=null;
  $('photo-editor').innerHTML=`<div class="card-heading"><div><p class="eyebrow">${p.id?'COMPLÉTER UNE OBSERVATION':'UNE NOUVELLE OBSERVATION'}</p><h2>${p.id?'Le contexte de cette photo':'Ajouter une photo'}</h2></div></div><form id="photo-form">${p.id?`<img class="photo-preview" src="${esc(p.image_url)}" alt="${esc(p.titre||'Photo à commenter')}">`:`<label class="photo-drop"><span aria-hidden="true">＋</span><strong>Choisir une photo sur ce PC</strong><small>JPEG, PNG ou WebP · 8 Mo maximum</small><input name="image" id="photo-file" type="file" accept="image/jpeg,image/png,image/webp" required></label><img class="photo-preview" id="photo-preview" alt="Aperçu de la photo choisie" hidden>`}<div class="fields">${field('Date et heure de prise de vue','date_photo',(p.date_photo||'').slice(0,16),'datetime-local','required')}<label class="field"><span>Emplacement</span><select name="zone">${Object.entries(zoneNames).map(([v,l])=>`<option value="${v}" ${(p.zone||'rayon')===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="field full"><span>Article concerné · facultatif pour une vue générale</span><select name="itm8">${photoArticleOptions(p.itm8||photoState.filterArticle)}</select></label><label class="field full"><span>Titre</span><input name="titre" maxlength="160" value="${esc(p.titre||'')}" placeholder="Ex. : nouvelle TG de raisins à l’entrée"></label><label class="field full"><span>Changement réalisé ou constat à expliquer</span><textarea name="changement" maxlength="2000" placeholder="Avant / après, largeur d’exposition, emplacement, remplissage, fraîcheur, signalétique, prix…">${esc(p.changement||'')}</textarea></label>${field('Promotion associée · début','promo_debut',p.promo_debut||'','date')}${field('Promotion associée · fin','promo_fin',p.promo_fin||'','date')}<div class="field full photo-auto"><span>Commentaire automatique de contexte</span><p id="photo-auto-text">${esc(p.commentaire_auto||'Renseignez la date et le contexte pour préparer le commentaire.')}</p><button type="button" class="text-button" id="photo-copy-auto">Utiliser et compléter ce texte ↗</button></div><label class="field full"><span>Votre commentaire corrigé ou complété</span><textarea name="commentaire" rows="5" maxlength="6000" placeholder="Décrivez ce que l’on voit et les conséquences que vous souhaitez vérifier dans les ventes.">${esc(p.commentaire||'')}</textarea></label></div><p class="form-help">Indiquez la date réelle de la photo. Les commentaires automatiques reprennent vos informations ; ils n’interprètent pas visuellement l’image. Les photos restent sur ce PC.</p><div class="form-actions"><span class="form-status" role="status"></span><button type="submit" class="primary">${p.id?'Enregistrer les compléments':'Ajouter au journal'}</button></div></form>`;
  const form=$('photo-form');form.addEventListener('submit',savePhoto);
  form.querySelectorAll('input,select,textarea').forEach(input=>input.addEventListener('input',()=>{state.dirty=true;photoState.retry=null;updatePhotoComment();}));
  $('photo-copy-auto').addEventListener('click',()=>{updatePhotoComment();form.elements.commentaire.value=$('photo-auto-text').textContent;state.dirty=true;photoState.retry=null;form.elements.commentaire.focus();});
  if($('photo-file'))$('photo-file').addEventListener('change',()=>{const file=$('photo-file').files[0];if(!file)return;if(file.size>8*1024*1024){setFormStatus(form,'La photo dépasse 8 Mo. Choisissez une version moins lourde.','error');$('photo-file').value='';photoState.file=null;return;}photoState.file=file;if(photoState.preview)URL.revokeObjectURL(photoState.preview);photoState.preview=URL.createObjectURL(file);$('photo-preview').src=photoState.preview;$('photo-preview').hidden=false;setFormStatus(form,'');});
}
function updatePhotoComment(){const f=$('photo-form');if(!f)return;const a=state.data?.articles.find(a=>a.itm8===f.elements.itm8.value);$('photo-auto-text').textContent=`Photo ${f.elements.date_photo.value?'du '+photoTime(f.elements.date_photo.value):'à dater'} · ${zoneNames[f.elements.zone.value]}${a?' · '+a.libelle:''}.${f.elements.changement.value.trim()?' Changement déclaré : '+f.elements.changement.value.trim():''}${f.elements.promo_debut.value&&f.elements.promo_fin.value?' Promotion associée du '+dateLabel(f.elements.promo_debut.value)+' au '+dateLabel(f.elements.promo_fin.value)+'.':''} Observation à rapprocher des ventes et de la disponibilité du produit, sans conclure à un lien de cause à effet.`;}
async function fileBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('La photo ne peut pas être lue.'));r.readAsDataURL(file);});}
async function savePhoto(event){
  event.preventDefault();const form=event.target;if(state.busy||!form.reportValidity())return;const f=Object.fromEntries(new FormData(form));delete f.image;
  if(new Date(f.date_photo)>new Date())return setFormStatus(form,'La date de prise de vue est dans le futur.','error');
  if(f.zone==='produit'&&!f.itm8)return setFormStatus(form,'Choisissez l’article photographié.','error');
  if(Boolean(f.promo_debut)!==Boolean(f.promo_fin)||f.promo_fin<f.promo_debut)return setFormStatus(form,'Vérifiez les deux dates de promotion.','error');
  state.busy=true;form.querySelectorAll('input,select,textarea,button').forEach(x=>x.disabled=true);$('refresh').disabled=true;setFormStatus(form,'Enregistrement de la photo et de son contexte…');
  try{
    let payload=photoState.retry;
    if(!payload){payload={...f,itm8:f.itm8||null,promo_debut:f.promo_debut||null,promo_fin:f.promo_fin||null,requete_id:crypto.randomUUID()};if(photoState.editing){payload.id=photoState.editing.id;payload.revision=photoState.editing.revision;}else{if(!photoState.file)throw new Error('Choisissez une photo.');payload.image_base64=await fileBase64(photoState.file);payload.nom_fichier=photoState.file.name;}photoState.retry=payload;}
    const result=await api('/api/photos-contexte',payload);state.dirty=false;photoState.retry=null;photoState.editing=result.photo;await loadPhotos();notice('Photo et contexte enregistrés sur ce PC. Aucune quantité de stock ou de commande n’a été modifiée.','success');window.scrollTo(0,0);
  }catch(error){setFormStatus(form,error.message,'error');notice(error.message,'error');}
  finally{state.busy=false;$('refresh').disabled=false;form.querySelectorAll('input,select,textarea,button').forEach(x=>x.disabled=false);}
}
$('photo-new').addEventListener('click',async()=>{if(!await canLeave())return;state.dirty=false;photoState.editing=null;photoState.retry=null;renderPhotoEditor();$('photo-editor').scrollIntoView({behavior:'smooth',block:'start'});});
for(const id of ['photo-zone-filter','photo-article-filter','photo-date-filter'])$(id).addEventListener('change',renderGallery);
$('photo-close').addEventListener('click',()=>$('photo-viewer').close());
document.addEventListener('click',async event=>{
  const target=event.target.closest('button');if(!target)return;
  if(target.dataset.photoOpen){const p=photoState.photos.find(p=>p.id===target.dataset.photoOpen);if(!p)return;$('photo-large').src=p.image_url;$('photo-large').alt=p.titre||zoneNames[p.zone];$('photo-large-caption').textContent=`${photoTime(p.date_photo)} · ${p.commentaire||p.commentaire_auto}`;$('photo-viewer').showModal();}
  if(target.dataset.photoEdit){if(!await canLeave())return;state.dirty=false;photoState.retry=null;photoState.editing=photoState.photos.find(p=>p.id===target.dataset.photoEdit);renderPhotoEditor();$('photo-editor').scrollIntoView({behavior:'smooth',block:'start'});}
  if(target.dataset.photoProduct){if(!await canLeave())return;state.dirty=false;photoState.filterArticle=target.dataset.photoProduct;photoState.editing=null;await changeView('photos');}
});
